### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by s10021205** [SrinivasMushnoori/RepEx_3.0#31]
(repex) jerry@jerry-VirtualBox:~/repex/examples/gromacs_example$ repex simconfig.json resconfig.json
Traceback (most recent call last):
  File "/home/jerry/VirtualEnvs/repex/repex/bin/repex", line 86, in <module>
    appman                  = AppManager(autoterminate=False, port=32769, resubmit_failed=True)  # Create Application Manager
  File "/home/jerry/VirtualEnvs/repex/repex/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 62, in __init__
    self._sid = ru.generate_id('re.session', ru.ID_PRIVATE)
  File "/home/jerry/VirtualEnvs/repex/repex/local/lib/python2.7/site-packages/radical/utils/ids.py", line 179, in generate_id
    return _generate_id(template, prefix, namespace)
  File "/home/jerry/VirtualEnvs/repex/repex/local/lib/python2.7/site-packages/radical/utils/ids.py", line 229, in _generate_id
    fd = os.open("%s/ru_%s_%s.cnt" % (state_dir, user, days), os.O_RDWR | os.O_CREAT)
OSError: [Errno 13] Permission denied: '/home/jerry/.radical/utils//ru_jerry_17960.cnt'

**Comment by s10021205** [comment]
![2019-03-05 10-35-54](https://user-images.githubusercontent.com/43686023/53817005-a0312200-3f32-11e9-8fab-0f8bd89aa356.png)

Hi, I am in the 'origin/usecase/peptide_gromacs'. 
But it shows the permission denied.

**Comment by SrinivasMushnoori** [comment]
1) Did you set up Rabbit MQ? You must install it to use EnTK. It's there in the user guide.
2) Are you attempting to run on localhost? If so, can you ssh into your own machine? This looks like a file system access issue.

**Comment by s10021205** [comment]
I will get back to you later!

**Comment by s10021205** [comment]
Hi Srinivas, I have already downloaded RabbitMQ. I am working on the machine at home. But the same error happened. 
![2019-03-05 20-16-15](https://user-images.githubusercontent.com/43686023/53848815-c632e280-3f83-11e9-9753-528ecd6c42a8.png)

**Comment by SrinivasMushnoori** [comment]
This seems to be a permissions issue. Are you sure your process has write permissions to your disk?
